/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import model.APOD;
import dal.DAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Objeto;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author Jal
 */
public class FrmProjeto extends javax.swing.JFrame {

    /**
     *
     * @throws ClassNotFoundException
     * @throws SQLException
     */

    APOD apod = dal.API.chamar("2024-07-01", "2024-07-07");
    ArrayList<Objeto> lst = dal.LeitorJSON.Leitor(apod);
    Timer timer = new Timer();

    public FrmProjeto() throws ClassNotFoundException, SQLException{
        initComponents();
        atualizaHora();
        contObjProx.setText(apod.element_count);
        carregaGrafico();
        carregaTabelaProxAprox();
        Timer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagemSobre = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mensagemPreferencias = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dataInicio = new javax.swing.JTextField();
        dataFim = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        abaResultados = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultados = new javax.swing.JTable();
        comboOrdenacao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contObjProx = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelData = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaProxAprox = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        menuArq = new javax.swing.JMenu();
        menuItemDashboard = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuDados = new javax.swing.JMenu();
        menuItemAtualizar = new javax.swing.JMenuItem();
        menuItemResult = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        menuItemPreferencias = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuItemSobre = new javax.swing.JMenuItem();

        mensagemSobre.setTitle("Sobre");
        mensagemSobre.setMinimumSize(new java.awt.Dimension(400, 150));

        jLabel4.setText("Desenvolvido por Júlia Roberta Quoos Alves");

        jLabel5.setText("Versão 1.0");

        javax.swing.GroupLayout mensagemSobreLayout = new javax.swing.GroupLayout(mensagemSobre.getContentPane());
        mensagemSobre.getContentPane().setLayout(mensagemSobreLayout);
        mensagemSobreLayout.setHorizontalGroup(
            mensagemSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensagemSobreLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(mensagemSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mensagemSobreLayout.setVerticalGroup(
            mensagemSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensagemSobreLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        mensagemPreferencias.setTitle("Preferências");
        mensagemPreferencias.setMinimumSize(new java.awt.Dimension(250, 200));

        jLabel2.setText("Data de início");

        jLabel6.setText("Data de fim");

        dataInicio.setText("AAAA-MM-DD");

        dataFim.setText("AAAA-MM-DD");

        jButton1.setText("Pesquisar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mensagemPreferenciasLayout = new javax.swing.GroupLayout(mensagemPreferencias.getContentPane());
        mensagemPreferencias.getContentPane().setLayout(mensagemPreferenciasLayout);
        mensagemPreferenciasLayout.setHorizontalGroup(
            mensagemPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensagemPreferenciasLayout.createSequentialGroup()
                .addGroup(mensagemPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mensagemPreferenciasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(mensagemPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mensagemPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dataFim)
                            .addComponent(dataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(mensagemPreferenciasLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        mensagemPreferenciasLayout.setVerticalGroup(
            mensagemPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensagemPreferenciasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mensagemPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mensagemPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        abaResultados.setTitle("Dados na database");
        abaResultados.setMinimumSize(new java.awt.Dimension(800, 500));

        tabelaResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados no Banco de Dados"));
        tabelaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Distancia", "Velocidade", "Tamanho", "Risco", "Próxima aproximação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaResultados.setMinimumSize(new java.awt.Dimension(0, 0));
        tabelaResultados.setOpaque(false);
        jScrollPane2.setViewportView(tabelaResultados);

        comboOrdenacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distancia", "Tamanho", "Velocidade", "Risco" }));
        comboOrdenacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrdenacaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Ordenar por:");

        javax.swing.GroupLayout abaResultadosLayout = new javax.swing.GroupLayout(abaResultados.getContentPane());
        abaResultados.getContentPane().setLayout(abaResultadosLayout);
        abaResultadosLayout.setHorizontalGroup(
            abaResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(abaResultadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaResultadosLayout.setVerticalGroup(
            abaResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verificação de objetos próximos à Terra");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador de objetos próximos"));

        contObjProx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contObjProx.setText("Número");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contObjProx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contObjProx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data/hora"));

        labelData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelData.setText("Data");

        labelHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelHora.setText("Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(labelHora)
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(labelHora))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Próximas aproximações"));
        jPanel3.setToolTipText("");

        tabelaProxAprox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Prox. Aprox.", "Distância (em km)", "Risco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaProxAprox);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Gráfico"));
        jPanel4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel4ComponentAdded(evt);
            }
        });
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        menu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuFocusGained(evt);
            }
        });
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
        });

        menuArq.setText("Arquivo");

        menuItemDashboard.setText("Dashboard");
        menuItemDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDashboardActionPerformed(evt);
            }
        });
        menuArq.add(menuItemDashboard);

        menuItemSair.setText("Sair");
        menuItemSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemSairMouseClicked(evt);
            }
        });
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArq.add(menuItemSair);

        menu.add(menuArq);

        menuDados.setText("Dados");

        menuItemAtualizar.setText("Atualizar dados");
        menuItemAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAtualizarActionPerformed(evt);
            }
        });
        menuDados.add(menuItemAtualizar);

        menuItemResult.setText("Resultados");
        menuItemResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemResultActionPerformed(evt);
            }
        });
        menuDados.add(menuItemResult);

        menu.add(menuDados);

        menuConfig.setText("Configurações");
        menuConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigActionPerformed(evt);
            }
        });

        menuItemPreferencias.setText("Preferências");
        menuItemPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPreferenciasActionPerformed(evt);
            }
        });
        menuConfig.add(menuItemPreferencias);

        menu.add(menuConfig);

        menuAjuda.setText("Ajuda");
        menuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaActionPerformed(evt);
            }
        });

        menuItemSobre.setText("Sobre");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuItemSobre);

        menu.add(menuAjuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuFocusGained

    }//GEN-LAST:event_menuFocusGained

    private void menuItemDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemDashboardActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAtualizarActionPerformed
    try {       
            carregaTabelaProxAprox();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrmProjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemAtualizarActionPerformed

    private void menuItemResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemResultActionPerformed
        abaResultados.setVisible(true);
        carregaTabelaResultados();
    }//GEN-LAST:event_menuItemResultActionPerformed

    private void menuItemSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemSairMouseClicked
        
    }//GEN-LAST:event_menuItemSairMouseClicked

    private void menuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaActionPerformed
       
    }//GEN-LAST:event_menuAjudaActionPerformed

    private void menuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSobreActionPerformed
        mensagemSobre.setVisible(true);
    }//GEN-LAST:event_menuItemSobreActionPerformed

    private void menuConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigActionPerformed
        
    }//GEN-LAST:event_menuConfigActionPerformed

    private void menuItemPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPreferenciasActionPerformed
        mensagemPreferencias.setVisible(true);
    }//GEN-LAST:event_menuItemPreferenciasActionPerformed

    private void comboOrdenacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrdenacaoActionPerformed
        carregaTabelaResultados();
    }//GEN-LAST:event_comboOrdenacaoActionPerformed

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
     
    }//GEN-LAST:event_menuMouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        apod = dal.API.chamar(dataInicio.getText(), dataFim.getText());
        contObjProx.setText(apod.element_count);
        
        try {
            carregaTabelaProxAprox();
            carregaTabelaResultados();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrmProjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jPanel4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel4ComponentAdded
        
    }//GEN-LAST:event_jPanel4ComponentAdded

    private void atualizaHora(){
        Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);
        labelData.setText(data);
        labelHora.setText(hora);
    }
    
    private void carregaTabelaProxAprox() throws ClassNotFoundException, SQLException {
        DefaultTableModel model = (DefaultTableModel) tabelaProxAprox.getModel();
        model.setRowCount(0);//limpar as linhas antigas da jTable
        
        String busca = (String) comboOrdenacao.getSelectedItem();
        ArrayList<Objeto> listaObj = DAO.consultar(busca);
         
        for (int i = 0; i < 6; i++){
            Object[] obj = new Object[4];//vetor para as 4 colunas
            obj[0] = listaObj.get(i).getNome();
            obj[1] = listaObj.get(i).getDataAprox();
            obj[2] = listaObj.get(i).getDistancia();
            obj[3] = listaObj.get(i).getRisco();
            model.addRow(obj);
        }
    }
    
    private void carregaTabelaResultados(){
        DefaultTableModel model = (DefaultTableModel) tabelaResultados.getModel();
        model.setRowCount(0);//limpar as linhas antigas da jTable
        
        
        String busca = (String) comboOrdenacao.getSelectedItem();
        try {
            ArrayList<Objeto> listaObj = DAO.consultar(busca);
            for (int i = 0; i < listaObj.size(); i++) {
                Object[] obj = new Object[6];//vetor para as 4 colunas
                obj[0] = listaObj.get(i).getNome();
                obj[1] = listaObj.get(i).getDistancia();
                obj[2] = listaObj.get(i).getVelocidade();
                obj[3] = listaObj.get(i).getTamanho();
                obj[4] = listaObj.get(i).getRisco();
                obj[5] = listaObj.get(i).getDataAprox();
                model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmProjeto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmProjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void carregaGrafico(){
        DefaultCategoryDataset barra = new DefaultCategoryDataset();
        try {
            ArrayList <Objeto> busca = DAO.consultarGrafico();
            for (int i=0; i < busca.size(); i++){
                barra.setValue( busca.get(i).setQnt(), busca.get(i).getDataAprox(), "");
            }

            JFreeChart grafico = ChartFactory.createBarChart3D("", "Data", "Objetos encontrados", barra, PlotOrientation.VERTICAL, true, true, false);
            ChartPanel painel = new ChartPanel(grafico);
            jPanel4.add(painel);
        } catch (SQLException ex) {
            System.out.println("deu erro na busca");
            Logger.getLogger(FrmProjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    public void Timer(){
        int delay = 0;
        int interval = 200;
        timer.scheduleAtFixedRate(new TimerTask(){
            public void run() {
               atualizaHora();
            }
        }, delay, interval);
    }
    
    

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmProjeto().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(FrmProjeto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame abaResultados;
    private javax.swing.JComboBox<String> comboOrdenacao;
    private javax.swing.JLabel contObjProx;
    private javax.swing.JTextField dataFim;
    private javax.swing.JTextField dataInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelHora;
    private javax.swing.JFrame mensagemPreferencias;
    private javax.swing.JFrame mensagemSobre;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArq;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenu menuDados;
    private javax.swing.JMenuItem menuItemAtualizar;
    private javax.swing.JMenuItem menuItemDashboard;
    private javax.swing.JMenuItem menuItemPreferencias;
    private javax.swing.JMenuItem menuItemResult;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JTable tabelaProxAprox;
    private javax.swing.JTable tabelaResultados;
    // End of variables declaration//GEN-END:variables
}
